name: Lint and Test workflow

on:
  push:
    branches:
      - main
      - JoeBranch
  pull_request:
    branches:
      - develop
      - staging
      - main
      - JoeBranch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: 🧰 Install Deps
        run: npm install

      - name: Run Lint
        run: npm run lint --prefix client

      - name: Run Build
        run: npm run build --prefix client

      - name: Run Tests
        run: npm run test --prefix client